# Basic
title: LiYong Blog
subtitle: Miracles happen every day.
welcome_message: 记录学习的点滴
description: Life was like a box of chocolates, you never know what you're going to get.
creator: <a href="http://zibo.one">@leeyongit</a>

url: "http://zibo.one"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: Blog
    description: 访问博客

nav:
    - {title: Bookmark, description: Favorites, url: 'http://zibo.one/bookmark'}
    - {title: About, description: About, url: 'http://zibo.one/about'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: leeyongit
    # duoshuo:
# Social
social:
    weibo: leeyongit
    github: leeyongit
    mail: leeyongit@163.com

# Google Analytics
ga:
    id: 
    host: zibo.one
