# Basic
title: Liyong's Blog
subtitle: 人生如梦，梦如人生
welcome_message: 记录学习的点滴
description: 嗨，我是李永 (@leeyongit)，一名来自中国的 PHP / Golang 开发者。现居北京。
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://liyong.life"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 关于, description: 了解更多关于我, url: 'http://liyong.life/about'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: leeyongit
    # duoshuo:
# Social
social:
    weibo: leeyongit
    github: leeyongit
    twitter: leeyongit
    gplus: 107108267983477358170
    mail: leeyongit@163.com

# Google Analytics
ga:
    id: UA-25719337-1
    host: liyong.life
