# Basic
title: Lee Yong
subtitle: Miracles happen every day.
welcome_message: 记录学习的点滴
description: 嗨，我是李永，一名 PHP/Golang 开发者。
creator: <a href="http://leeyongit.github.io">@leeyongit</a>

url: "https://leeyongit.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: Blog
    description: 访问博客

nav:
    - {title: Bookmark, description: Favorites, url: 'https://leeyongit.github.io/bookmark'}
    - {title: About, description: About, url: 'http://leeyongit.github.io/about'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: leeyongit
    # duoshuo:
# Social
social:
    # weibo: leeyongit
    github: leeyongit
    mail: leeyongit@163.com

# Google Analytics
ga:
    id: 
    host: leeyongit.github.io
